# Each monitor line: <name>,<mode>,<position>,<scale>

monitor = eDP-1, 2880x1800@120, auto, 1.5          # 14”  WQHD 120 Hz
#monitor = eDP-1, disabled          # 14”  WQHD 120 Hz
monitor = DP-2, 2560x1440@165, auto, 1       # 27” 1440p 165 Hz
#monitor = HDMI-A-1, 2560x1440@144, auto, 1.25
#monitor = HDMI-A-1, 1366x768@60, auto, 1
