# Rule helpers

windowrulev2 = float,title:(?i)picture.?in.?picture
windowrulev2 = pin,title:(?i)picture.?in.?picture
windowrulev2 = float,title:(Open|Save) File(s?)
windowrulev2 = float,class:(org.telegram.desktop|mpv|org.kde.konsole)
windowrulev2 = size 1343 899,class:(org.telegram.desktop)
windowrulev2 = idleinhibit fullscreen,class:^(.*)$,title:^(.*)$,fullscreen:1

# Games

windowrulev2 = tag +games,class:^(marvel-win64-shipping.exe)$
windowrulev2 = immediate,tag:games*
windowrulev2 = fullscreen,tag:games*
windowrulev2 = allowsinput,tag:games*
windowrulev2 = content game,tag:games*

# Workspace hints

windowrulev2 = workspace 3 silent,class:^(keepassxc)$
windowrulev2 = workspace 3 silent,class:^(org.kde.dolphin)$
