# Rule helpers

windowrule = match:title (?i)picture.?in.?picture, float on
windowrule = match:title (?i)picture.?in.?picture, pin on
windowrule = match:title (Open|Save) File(s?), float on
windowrule = match:class (xdg-desktop-portal-gtk), float on
windowrule = match:class (org.telegram.desktop|mpv|org.kde.konsole), float on
windowrule = match:class (org.telegram.desktop), size 1343 899
windowrule = match:class ^(.*)$, match:title ^(.*)$, match:fullscreen 1, idle_inhibit fullscreen

# Games

# windowrule = tag +games, match:class ^(marvel-win64-shipping.exe)$
# windowrule = tag games, immediate on
# windowrule = tag games, fullscreen on
# windowrule = tag games, allowsinput on
# windowrule = tag games, content game

# Workspace hints

# windowrule = workspace 3 silent,class:^(keepassxc)$
# windowrule = workspace 3 silent,class:^(org.kde.dolphin)$
